spring.application.name=uctale

google.ai.api-key=${GOOGLE_AI_API_KEY}
pollinations.token=${POLLINATIONS_TOKEN}
game.access.password=${GAME_ACCESS_PASSWORD}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true

server.port=${PORT:8080}
