package com.uctale.uctale.application.game;

import com.uctale.uctale.domain.game.CharacterStats;
import com.uctale.uctale.domain.game.CharacterVitals;
import com.uctale.uctale.domain.game.EnemyCombatProfile;
import org.springframework.stereotype.Component;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.node.JsonNodeFactory;
import tools.jackson.databind.node.ObjectNode;

@Component
public class GameStateUpgrader {
    public UpgradedSnapshot upgrade(JsonNode snapshotJson) {
        VersionedState v=readSourceVersion(snapshotJson); while(v.schemaVersion()<GameStateSnapshotFormat.CURRENT_SCHEMA_VERSION)v=upgradeOneVersion(v); validateCurrentShape(v.state()); return new UpgradedSnapshot(v.schemaVersion(),v.rulesetVersion(),v.state());
    }
    private VersionedState readSourceVersion(JsonNode j){if(j==null||!j.isObject())throw new GameStateSnapshotException("GameState snapshot JSON object가 필요합니다.");if(!j.has("schemaVersion")){if(!looksLikeLegacyState(j))throw new GameStateSnapshotException("snapshot schemaVersion이 누락되었습니다.");return new VersionedState(0,1,j);}int s=requiredInteger(j,"schemaVersion");if(s>6)throw new GameStateSnapshotException("지원하지 않는 미래 snapshot schemaVersion입니다: "+s);if(s<1)throw new GameStateSnapshotException("유효하지 않은 snapshot schemaVersion입니다: "+s);int r=requiredInteger(j,"rulesetVersion");if(r!=1)throw new GameStateSnapshotException("지원하지 않는 snapshot rulesetVersion입니다: "+r);JsonNode state=j.get("state");if(state==null||!state.isObject())throw new GameStateSnapshotException("snapshot state가 누락되었거나 손상되었습니다.");return new VersionedState(s,r,state);}
    private VersionedState upgradeOneVersion(VersionedState s){return switch(s.schemaVersion()){case 0->upgradeV0ToV1(s);case 1->upgradeV1ToV2(s);case 2->upgradeV2ToV3(s);case 3->upgradeV3ToV4(s);case 4->upgradeV4ToV5(s);case 5->upgradeV5ToV6(s);default->throw new GameStateSnapshotException("snapshot schemaVersion "+s.schemaVersion()+"의 다음 upgrade 경로가 없습니다.");};}
    private VersionedState upgradeV0ToV1(VersionedState s){return new VersionedState(1,s.rulesetVersion(),s.state());}
    private VersionedState upgradeV1ToV2(VersionedState s){ObjectNode state=objectCopy(s.state());JsonNode p=state.get("playerCharacter");if(!(p instanceof ObjectNode player))throw new GameStateSnapshotException("snapshot playerCharacter가 누락되었거나 손상되었습니다.");JsonNode old=player.get("stats");if(old!=null&&!old.isObject())throw new GameStateSnapshotException("snapshot playerCharacter.stats가 object가 아닙니다.");ObjectNode stats=JsonNodeFactory.instance.objectNode();stats.put("might",legacyScore(old,"MIGHT","might"));stats.put("agility",legacyScore(old,"AGILITY","agility"));stats.put("intellect",legacyScore(old,"INTELLECT","intellect"));stats.put("will",legacyScore(old,"WILL","will"));stats.put("presence",legacyScore(old,"PRESENCE","presence"));player.set("stats",stats);return new VersionedState(2,s.rulesetVersion(),state);}
    private VersionedState upgradeV2ToV3(VersionedState s){ObjectNode state=objectCopy(s.state());if(state.has("inventory"))throw new GameStateSnapshotException("schema v2 snapshot에는 inventory 필드가 정의되어 있지 않습니다.");ObjectNode inv=JsonNodeFactory.instance.objectNode();inv.set("items",JsonNodeFactory.instance.objectNode());ObjectNode eq=JsonNodeFactory.instance.objectNode();eq.set("slots",JsonNodeFactory.instance.objectNode());inv.set("equipment",eq);state.set("inventory",inv);return new VersionedState(3,s.rulesetVersion(),state);}
    private VersionedState upgradeV3ToV4(VersionedState s){ObjectNode state=objectCopy(s.state());JsonNode p=state.get("playerCharacter");if(!(p instanceof ObjectNode player))throw new GameStateSnapshotException("snapshot playerCharacter가 누락되었거나 손상되었습니다.");if(player.has("vitals"))throw new GameStateSnapshotException("schema v3 snapshot에는 playerCharacter.vitals 필드가 정의되어 있지 않습니다.");ObjectNode vitals=JsonNodeFactory.instance.objectNode();vitals.set("hp",fullPool(CharacterVitals.DEFAULT_MAX_HP));vitals.set("mp",fullPool(CharacterVitals.DEFAULT_MAX_MP));vitals.set("statusEffects",JsonNodeFactory.instance.objectNode());player.set("vitals",vitals);return new VersionedState(4,s.rulesetVersion(),state);}
    private VersionedState upgradeV4ToV5(VersionedState s){ObjectNode state=objectCopy(s.state());if(state.has("combatEncounter"))throw new GameStateSnapshotException("schema v4 snapshot에는 combatEncounter 필드가 정의되어 있지 않습니다.");state.set("combatEncounter",JsonNodeFactory.instance.nullNode());return new VersionedState(5,s.rulesetVersion(),state);}
    private VersionedState upgradeV5ToV6(VersionedState s){ObjectNode state=objectCopy(s.state());JsonNode invNode=state.get("inventory");if(!(invNode instanceof ObjectNode inv))throw new GameStateSnapshotException("schema v5 snapshot inventory가 누락되었거나 손상되었습니다.");JsonNode itemsNode=inv.get("items");if(!(itemsNode instanceof ObjectNode items))throw new GameStateSnapshotException("schema v5 snapshot inventory.items가 누락되었거나 손상되었습니다.");for(var e:items.properties()){if(!(e.getValue() instanceof ObjectNode item))throw new GameStateSnapshotException("schema v5 snapshot inventory item이 object가 아닙니다.");JsonNode dNode=item.get("definition");if(!(dNode instanceof ObjectNode d))throw new GameStateSnapshotException("schema v5 snapshot item definition이 누락되었거나 손상되었습니다.");if(d.has("combatModifiers"))throw new GameStateSnapshotException("schema v5 snapshot에는 item combatModifiers가 정의되어 있지 않습니다.");ObjectNode m=JsonNodeFactory.instance.objectNode();m.put("attackBonus",0);m.put("damageBonus",0);d.set("combatModifiers",m);}JsonNode cNode=state.get("combatEncounter");if(cNode==null)throw new GameStateSnapshotException("schema v5 snapshot combatEncounter 필드가 누락되었습니다.");if(!cNode.isNull()){if(!(cNode instanceof ObjectNode combat))throw new GameStateSnapshotException("schema v5 snapshot combatEncounter가 object가 아닙니다.");JsonNode enemiesNode=combat.get("enemies");if(!(enemiesNode instanceof ObjectNode enemies))throw new GameStateSnapshotException("schema v5 snapshot combatEncounter.enemies가 누락되었거나 손상되었습니다.");for(var e:enemies.properties()){if(!(e.getValue() instanceof ObjectNode enemy))throw new GameStateSnapshotException("schema v5 snapshot enemy가 object가 아닙니다.");if(enemy.has("combatProfile"))throw new GameStateSnapshotException("schema v5 snapshot에는 enemy combatProfile이 정의되어 있지 않습니다.");ObjectNode p=JsonNodeFactory.instance.objectNode();p.put("defenseScore",EnemyCombatProfile.DEFAULT_DEFENSE_SCORE);p.put("damageReduction",EnemyCombatProfile.DEFAULT_DAMAGE_REDUCTION);enemy.set("combatProfile",p);}}return new VersionedState(6,s.rulesetVersion(),state);}
    private void validateCurrentShape(JsonNode state){if(!state.has("combatEncounter"))throw new GameStateSnapshotException("현재 schema snapshot combatEncounter 필드가 누락되었습니다.");JsonNode invNode=state.get("inventory");if(!(invNode instanceof ObjectNode inv)||!(inv.get("items") instanceof ObjectNode items))throw new GameStateSnapshotException("현재 schema snapshot inventory/items가 누락되었거나 손상되었습니다.");for(var e:items.properties()){JsonNode d=e.getValue().get("definition");if(d==null||!d.isObject()||!d.has("combatModifiers"))throw new GameStateSnapshotException("현재 schema snapshot item combatModifiers가 누락되었습니다.");}JsonNode c=state.get("combatEncounter");if(c!=null&&!c.isNull()){JsonNode enemies=c.get("enemies");if(enemies==null||!enemies.isObject())throw new GameStateSnapshotException("현재 schema snapshot combat enemies가 누락되었거나 손상되었습니다.");for(var e:enemies.properties()){JsonNode enemy=e.getValue();if(enemy==null||!enemy.isObject()||!enemy.has("combatProfile"))throw new GameStateSnapshotException("현재 schema snapshot enemy combatProfile이 누락되었습니다.");}}}
    private ObjectNode objectCopy(JsonNode s){if(!(s.deepCopy() instanceof ObjectNode c))throw new GameStateSnapshotException("snapshot state가 object가 아닙니다.");return c;}private ObjectNode fullPool(int max){ObjectNode p=JsonNodeFactory.instance.objectNode();p.put("current",max);p.put("max",max);return p;}
    private int legacyScore(JsonNode stats,String enumKey,String fieldKey){if(stats==null)return CharacterStats.DEFAULT_SCORE;JsonNode v=stats.get(fieldKey);if(v==null)v=stats.get(enumKey);if(v==null)return CharacterStats.DEFAULT_SCORE;if(!v.isIntegralNumber())throw new GameStateSnapshotException("snapshot 능력치 "+enumKey+"가 정수가 아닙니다.");long score=v.asLong();if(score<CharacterStats.MIN_SCORE||score>CharacterStats.MAX_SCORE)throw new GameStateSnapshotException("snapshot 능력치 "+enumKey+"가 허용 범위를 벗어났습니다: "+score);return(int)score;}
    private boolean looksLikeLegacyState(JsonNode j){return j.has("turnNumber")&&j.has("playerCharacter")&&j.has("worldState")&&j.has("storyMemory")&&!j.has("rulesetVersion")&&!j.has("state");}
    private int requiredInteger(JsonNode j,String f){JsonNode v=j.get(f);if(v==null||!v.isIntegralNumber())throw new GameStateSnapshotException("snapshot "+f+"이 누락되었거나 정수가 아닙니다.");long n=v.asLong();if(n<Integer.MIN_VALUE||n>Integer.MAX_VALUE)throw new GameStateSnapshotException("snapshot "+f+"이 지원 범위를 벗어났습니다: "+n);return(int)n;}
    private record VersionedState(int schemaVersion,int rulesetVersion,JsonNode state){}
    public record UpgradedSnapshot(int schemaVersion,int rulesetVersion,JsonNode state){}
}
