create table game_session (
    id bigint generated by default as identity primary key,
    world_setting varchar(255) not null,
    character_setting varchar(255) not null,
    is_game_over boolean not null default false,
    current_turn integer not null default 1,
    version bigint not null default 0,
    created_at timestamp,
    updated_at timestamp
);

create table game_log (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    turn_number integer not null,
    story_text text,
    choices_json text,
    image_url text,
    user_choice varchar(255),
    created_at timestamp,
    constraint fk_game_log_session
        foreign key (session_id) references game_session(id) on delete cascade,
    constraint uk_game_log_session_turn
        unique (session_id, turn_number)
);

create index idx_game_log_session_turn
    on game_log(session_id, turn_number desc);
