CREATE TABLE provider_usage_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    operation VARCHAR(64) NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    attempt_count INTEGER NOT NULL,
    budget_units BIGINT NOT NULL,
    CONSTRAINT ck_provider_usage_attempt_count CHECK (attempt_count >= 1),
    CONSTRAINT ck_provider_usage_budget_units CHECK (budget_units >= 1)
);

CREATE INDEX idx_provider_usage_occurred_at
    ON provider_usage_event (occurred_at);

CREATE INDEX idx_provider_usage_dimensions
    ON provider_usage_event (provider, model, operation, occurred_at);
